### ISSUE TITLE
Error when installing in windows using pip3

### ISSUE THREAD

**Issue by Knowif** [donnemartin/gitsome#114] opened 2017-03-24 12:31 UTC
```
$ pip3 install gitsome
Collecting gitsome
  Downloading gitsome-0.6.0.tar.gz (308kB)
Collecting numpydoc<1.0,>=0.5 (from gitsome)
  Downloading numpydoc-0.6.0.tar.gz
Collecting ply<4.0,>=3.4 (from gitsome)
  Downloading ply-3.10.tar.gz (150kB)
Collecting prompt-toolkit<1.1.0,>=1.0.0 (from gitsome)
  Downloading prompt_toolkit-1.0.13-py3-none-any.whl (247kB)
Collecting requests<3.0.0,>=2.8.1 (from gitsome)
  Downloading requests-2.13.0-py2.py3-none-any.whl (584kB)
Collecting colorama<1.0.0,>=0.3.3 (from gitsome)
  Downloading colorama-0.3.7-py2.py3-none-any.whl
Collecting click<7.0,>=5.1 (from gitsome)
  Downloading click-6.7-py2.py3-none-any.whl (71kB)
Collecting pygments<3.0.0,>=2.0.2 (from gitsome)
  Downloading Pygments-2.2.0-py2.py3-none-any.whl (841kB)
Collecting feedparser<6.0.0,>=5.2.1 (from gitsome)
  Downloading feedparser-5.2.1.zip (1.2MB)
Collecting pytz<2017.0,>=2016.3 (from gitsome)
  Downloading pytz-2016.10-py2.py3-none-any.whl (483kB)
Collecting docopt<1.0.0,>=0.6.2 (from gitsome)
  Downloading docopt-0.6.2.tar.gz
Collecting uritemplate.py<1.0.0,>=0.2.0 (from gitsome)
  Downloading uritemplate.py-0.3.0.tar.gz
Collecting wcwidth (from prompt-toolkit<1.1.0,>=1.0.0->gitsome)
  Downloading wcwidth-0.1.7-py2.py3-none-any.whl
Collecting six>=1.9.0 (from prompt-toolkit<1.1.0,>=1.0.0->gitsome)
  Downloading six-1.10.0-py2.py3-none-any.whl
Installing collected packages: numpydoc, ply, wcwidth, six, prompt-toolkit, requests, colorama, click, pygments, feedparser, pytz, docopt, uritemplate.py, gitsome
  Running setup.py install for numpydoc: started
    Running setup.py install for numpydoc: finished with status 'done'
  Running setup.py install for ply: started
    Running setup.py install for ply: finished with status 'done'
  Running setup.py install for feedparser: started
    Running setup.py install for feedparser: finished with status 'done'
  Running setup.py install for docopt: started
    Running setup.py install for docopt: finished with status 'done'
  Running setup.py install for uritemplate.py: started
    Running setup.py install for uritemplate.py: finished with status 'done'
  Running setup.py install for gitsome: started
    Running setup.py install for gitsome: finished with status 'error'
    Complete output from command d:\python\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-build-huk1342w\\gitsome\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\ADMINI~1\AppData\Local\Temp\pip-ablzusfp-record\install-record.txt --single-version-externally-managed --compile:

    running install
    Remove xonsh/parser_table.py
    Building lexer and parser tables.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-huk1342w\gitsome\setup.py", line 129, in <module>
        main()
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-huk1342w\gitsome\setup.py", line 122, in main
        setup(**skw)
      File "d:\python\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "d:\python\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "d:\python\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-huk1342w\gitsome\setup.py", line 44, in run
        build_tables()
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-huk1342w\gitsome\setup.py", line 37, in build_tables
        outputdir='xonsh')
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-huk1342w\gitsome\xonsh\parser.py", line 233, in __init__
        self.parser = yacc.yacc(**yacc_kwargs)
      File "d:\python\lib\site-packages\ply\yacc.py", line 3426, in yacc
        raise YaccError('Unable to build parser')
    ply.yacc.YaccError: Unable to build parser

    ----------------------------------------
Command "d:\python\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-build-huk1342w\\gitsome\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\ADMINI~1\AppData\Local\Temp\pip-ablzusfp-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-huk1342w\gitsome\

 ```

**Comment by donnemartin** [comment] 2017-03-25 02:31
Hi @Knowif, thanks for the bug report!  This seems to be a dupe of https://github.com/donnemartin/gitsome/issues/105.  Let's track the issue there.  Thanks!

**Closed by donnemartin** 2017-03-25 02:31 UTC
Labels: duplicate
